# Develop a python program to demonstrate sequence execution (avg of three numbers)
num1 = float(input("Enter the first number : "))
num2 = float(input("Enter the second number : "))
num3 = float(input("Enter the third number : "))
print("Average : ",((num1+num2+num3)/3))